# Append to bash_profile

# Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries
#
# If you need to have this software first in your PATH run:
#    echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile
#
# For compilers to find this software you may need to set:
#    LDFLAGS:  -L/usr/local/opt/openssl/lib
#    CPPFLAGS: -I/usr/local/opt/openssl/include
# export PATH="/usr/local/opt/openssl/bin:$PATH"

# Add personal bin
export PATH="/Users/jjw/bin:$PATH"

export TERM="xterm-color"

. ~/.bash_prompt
